### ISSUE TITLE
Advantage and disadvantage rolls

### ISSUE THREAD

**Issue by pplurueda** [free-beer/black-sword-hack#11]
Is it possible to make advantage and disadvantage rolls? If so, please tell me how.

**Comment by free-beer** [comment]
Hold the Shift key when clicking on a roll icon will make the roll with advantage. Likewise, hold the Ctrl key will roll with Disadvantage.

**Comment by free-beer** [comment]
I guess I should add that you can also use the Alt key on some icons to open a dialog that allows for a more complex roll.
