### ISSUE TITLE
Fairy Tales

### ISSUE THREAD

**Issue by IgorAthen** [free-beer/black-sword-hack#20]
Hello!

I apologize in advance for my English. Please tell me, do I understand correctly that there is no section for fairy gifts? They appear when using the Changeling backstory.

I would also like to offer my help as a translator into Russian. If this is relevant - provide me with a file with all the words and phrases that need to be translated and I will translate them for you.

Thank you!

**Comment by free-beer** [comment]
Hi,

It's true that I have not implemented fairy gifts in the system. To be totally honest, I've not got the time to give this system any attention lately and have just been keep things running with new versions. It's unlikely to change any time soon, so there's not much chance of me implementing gifts unfortunately. With regards to translations, if you look at the root of the repository you'll see there is a languages folder. To translate it you need to provide a Russian version of the en.json that's found in this folder. I will note that, if I ever do start adding functionality to the system again, I will only ever be able to add English text, so the level of translation will deteriorate unless someone comes back and regularly updates these files - just letting you know what 'volunteering' to do translations means.

Regards,
Peter

**Comment by IgorAthen** [comment]
Can you please tell me what I should have said to finally finish the character sheet for this system? I would be happy to donate to you, but paypal doesn't work in my country.

I would also be grateful if you could explain how to select the suggested birthplace in the sheet? Or does it only work with random generation?

Could we contact in any messenger to discuss the details of the translation and other things?

**Comment by free-beer** [comment]
Not making any promises about implementing any functionality, apologies. With regards to the birthplace, I left this as a free form text field as it means that you can invent your own birth places. You can freely type in one of the ones from the rules and the random generator uses that list.

With regards to the translation, here's what's needed...
 - Clone the repo.
 - Go into the ``languages`` folder.
 - Copy the ``en.json`` file to something like ``ru.json``.
 - Open this new ``ru.json`` in a text editor and convert all the parts after ``:``'s in the file to Russian (don't remove the ``'"'`` around each entry!).
 - When you're done, let me know. If you know how, you can open a PR. If not we can maybe work something out.
 - I will then incorporate your language file and do a new release.

**Comment by IgorAthen** [comment]
[ru.json](https://github.com/user-attachments/files/17682050/ru.json)

**Comment by free-beer** [comment]
Okay, the Russian translations file has been incorporated. I had to add some styling because some of the translations run long for the space available and I've only done minimal checking that it's showing properly. The new version is v1.2.6.

**Comment by IgorAthen** [comment]
![изображение](https://github.com/user-attachments/assets/2e4fc774-2d0f-42a9-b549-1066afb822c3)
![изображение](https://github.com/user-attachments/assets/6b62f300-70b8-41e5-a3a1-9ef47b1687d6)

Hi! I'll make some adjustments to the translation to make it more original, okay? Unfortunately, I just now found some bad solutions. Please tell me why the backgrounds and origins were not translated? I also wanted to translate the background descriptions, they were not in the translation file, how can I do this? Thanks for the prompt answers!

**Comment by free-beer** [comment]
The answer is, unfortunately, because the text for these is actually in the code. To fix this I would need to incorporate a translation capability for them. I might get the time to do this, I might not - like I said I'm not committing to making any substantial, non-fix code changes.

**Comment by IgorAthen** [comment]
![изображение](https://github.com/user-attachments/assets/9bfa156a-8047-4583-a5a4-e61650860197)
Hi! I also noticed that when choosing Gifts, they are not transferred to the main character sheet.

**Comment by free-beer** [comment]
**NOTE:** This is the last comment on this issue, please don't post anymore here as it is closed.

The gift thing is working as expected. Selecting a gift is simply intended to reflect your choice upon reaching the level. The gift itself needs to be added to the character separately. There are a bunch of issues about automating that, so I've bypassed them by simply not automating it at all. I won't be changing this.

The background descriptions are, from version 1.2.7, now translatable. These descriptions contain HTML markup tags and, if you're planning on translating them, then you will have to work around these.
