### ISSUE TITLE
Change Request: On the Front Page list the Power of each gift

### ISSUE THREAD

**Issue by WisdomOfWombats** [free-beer/black-sword-hack#4]
On the front page, you get an overview of the Gifts in the Gifts section. That section lists currently only the name of the Gift. But since sometimes it's nice to know, if a character aligns with Law, Balance or Chaos, it would be nice to see the Power listed in addition to the name.

**Comment by free-beer** [comment]
Okay, will add this to the next release.

**Comment by free-beer** [comment]
Implemented in v1.0.1.
